# Parmigiano Configuration File 

# Phenotype data
expression_path: '/gpfs/commons/groups/knowles_lab/vmazeeva/BigBrain/Processed/tpm_genes_subset.tsv'
covariates_path: '/gpfs/commons/groups/knowles_lab/vmazeeva/BigBrain/Processed/covariates.tsv'
diagnosis_col: Diagnosis
sample_col: SampleID

# Genotype and annotation data (Option 2: Individual gene files)
genotype_dir: '/gpfs/commons/groups/knowles_lab/vmazeeva/BigBrain/Processed/genotypes/'
annotation_dir: '/gpfs/commons/groups/knowles_lab/vmazeeva/BigBrain/Processed/annotations/'
gene_list: '/gpfs/commons/home/vmazeeva/firvTWAS/parmigiano-expr/src/gene_list_3.txt'

# Bayesian Ridge Regression results
brr_results_dir: "/gpfs/commons/home/adas/uTWAS/src/results/baseline_full/bayesian_ridge"

# Train/Test split
train_test: True

# Model parameters
maf_beta: 1  # Beta parameter for MAF weights
lr: 0.01   # Learning rate
epochs: 500  # Number of training epochs
n_posterior: 50  # Number of posterior samples
refits: 100
tau1_intercept: True
common_variants_only: True
maf_threshold: 0.05

# Output
output_dir: seed_genes_minmax